parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $omdbApiKey: "%env(OMDB_API_KEY)%"
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
